# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputBodyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnant', models.DecimalField(decimal_places=15, max_digits=25)),
                ('skinfold', models.DecimalField(decimal_places=15, max_digits=25)),
                ('seruminsulin', models.DecimalField(decimal_places=15, max_digits=25)),
                ('bmi', models.DecimalField(decimal_places=15, max_digits=25)),
                ('pedigree', models.DecimalField(decimal_places=15, max_digits=25)),
                ('age', models.DecimalField(decimal_places=15, max_digits=25)),
                ('inputdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestBodyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.DecimalField(decimal_places=15, max_digits=25)),
                ('bloodpresure', models.DecimalField(decimal_places=15, max_digits=25)),
                ('testdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='arduinoboard',
            name='board',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
