# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0002_auto_20171002_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbodystatus',
            old_name='bloodpresure',
            new_name='bloodpressure',
        ),
    ]
