# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbodystatus',
            name='arduino',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
